
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 23 01:58:40 EEST 2011
//----------------------------------------------------

package demogame;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int gustav = 37;
  public static final int talk = 25;
  public static final int toss = 40;
  public static final int pull = 23;
  public static final int goblin = 28;
  public static final int hammer = 6;
  public static final int at = 12;
  public static final int look = 35;
  public static final int an = 10;
  public static final int go = 19;
  public static final int wall = 15;
  public static final int talkto = 31;
  public static final int pillowcase = 34;
  public static final int examine = 24;
  public static final int gotu = 20;
  public static final int princess = 30;
  public static final int kill = 26;
  public static final int workbench = 16;
  public static final int hallway = 27;
  public static final int take = 3;
  public static final int drop = 38;
  public static final int then = 11;
  public static final int open = 21;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int axe = 7;
  public static final int back = 32;
  public static final int the = 8;
  public static final int on = 13;
  public static final int boss = 29;
  public static final int hug = 36;
  public static final int door = 18;
  public static final int window = 33;
  public static final int dismiss = 39;
  public static final int push = 22;
  public static final int and = 14;
  public static final int candle = 5;
  public static final int use = 2;
  public static final int get = 4;
  public static final int chair = 17;
  public static final int a = 9;
}

