
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 11 12:31:44 EEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int DOOR = 2;
  public static final int OPEN = 3;
  public static final int EOF = 0;
}

